manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson/zmk
  projects:
    - name: zmk
      remote: petejohanson
      revision: shields/splitkb_aurora_sweep
      import: app/west.yml
  self:
    path: config
